spring:
  application:
    name: blog

  datasource:
    url: jdbc:postgresql://localhost:5400/mydatabase
    username: myuser
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true

jwt:
  secret: your-256-bit-secret-key-here-make-it-at-least-32-bytes-long